### PR TITLE
fix: uncheck senate state dhhl by default

### LINKED ISSUE #59: [TASK] All overlays default to `unchecked`
# Overview
Currently the Federal, State, and DHHL overlays are checked/on by default on page load.

# Action
Modify the behavior so that the page loads with them unchecked/off.

## Resources
[Hawaii-Zoning-Atlas](https://github.com/CodeforHawaii/Hawaii-Zoning-Atlas)/[scripts](https://github.com/CodeforHawaii/Hawaii-Zoning-Atlas/tree/main/scripts)/map.js
`lines 101-104`

overlay-current-default

### PR DESCRIPTION
**Pull request by TyPushesButtons**
senate, state, and DHHL are unchecked by default and will not be active when first loading the webpage.

### CODE REVIEW

File: scripts/map.js [hunk 1]
```diff
@@ -98,10 +98,10 @@ var loadZones = function (geojson) {
...
   }).addTo(map)
 
-  // Turn on federal/state land by default
-  $('input[name="Overlay"][value="federal"]').prop('checked', true)
-  $('input[name="Overlay"][value="state"]').prop('checked', true)
-  $('input[name="Overlay"][value="DHHL"]').prop('checked', true)
+  // Turn off federal/state land by default
+  $('input[name="Overlay"][value="federal"]').prop('checked', false)
+  $('input[name="Overlay"][value="state"]').prop('checked', false)
+  $('input[name="Overlay"][value="DHHL"]').prop('checked', false)
```
Comment (tyliec) [inline scripts/map.js]:
```suggestion
```

Perhaps it would just be better to just delete these lines

**Review by tyliec — APPROVED** [review]

File: scripts/map.js (hunk 1 above)
Comment (TyPushesButtons) [reply scripts/map.js]: will we never toggle these on start up in the future?

Comment (tyliec) [reply scripts/map.js]: They are unchecked by default

Comment (tyliec) [reply scripts/map.js]: IMO it's better to just delete them since we can add these lines back anyway if we are going to toggle them on start - leaving them in while basically just preserving the default behaviour is just confusing
