### PR TITLE
Fixing the default color for not zoned areas

### LINKED ISSUE #96: Color Issue
### Overview

Blue is used for roads and streets. In map-making, its a rule that blue should only be used for water. Streets are almost always red, black or grey. Apologies I thought this was already identified and resolved with UX colors. 

### Action Items

Change blue of streets and roads to accepted symbol colors. This includes black and grey, and sometimes red for highways. Any of these will be better and match symbology rules. 

### Resources/Instructions
The USGS has a great symbology type in PDF. https://edrnet.com/wp-content/uploads/2014/08/US-Topo-Map-Symbols.pdf

### PR DESCRIPTION
**Pull request by avenmia**
The "Not Zoned" areas are blue by default. Blue is reserved for waterways according to:  https://edrnet.com/wp-content/uploads/2014/08/US-Topo-Map-Symbols.pdf

I updated the color to be a light grey instead.

This closes #96 

image

### CODE REVIEW

File: scripts/map.js [hunk 1]
```diff
@@ -54,6 +61,7 @@ var loadZones = function (geojson) {
 
       // On layer click, select town
       layer.on('click', function () {
+        console.log("PP:", pp)
```
Comment (airyclam) [inline scripts/map.js]: [q] Is this log supposed to be here? If it is, should we be clearer on what is PP?

File: scripts/map.js [hunk 2]
```diff
@@ -20,13 +20,20 @@ var zAcres = 'MA' // municipal area
...
 var style = function (filters, feature) {
   var opacity = $('input[name="opacity"]').val() / 100
-
+  let fillColor = satisfiesFilters(filters, feature)
+  ? zone2color[feature.properties[zType]]
+  : zone2color['NS'];
+
+  // If the feature is "Not Zoned" the properties[zType] will be null
+  // This fixes the null areas being blue by default
+  if(feature.properties[zType] === null)
```
Comment (airyclam) [inline scripts/map.js:30]: [Suggestion] can we instead modify satisfiesFilters() to handle the null case? This might clean up some code here and we won't have to hardcode fillColor here, we'd be able to use the zone2color map above instead.

File: scripts/map.js (hunk 1 above)
Comment (avenmia) [reply scripts/map.js]: Good catch, just removed it 👍

File: scripts/map.js (hunk 2 above)
Comment (avenmia) [reply scripts/map.js:30]: I'm not sure how satisfiesFilters returning true for the null case would affect the following:
```
dataLayer.eachLayer(function (l) {
    if (l.feature.properties[zTown] === townActive) {
      totalAcres += l.feature.properties[zAcres] || 0
      if (satisfiesFilters(filters, l.feature)) {
        satisfiesAcres += l.feature.properties[zAcres] || 0
      }
    }
  })
```

Comment (avenmia) [reply scripts/map.js:30]: I moved the hardcoded value into zone2color so they're at least all in one spot. Let me know what you think

**Review by airyclam — APPROVED** [review]
looks good
